//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Translator.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryRecord
    {
        public int RecordId { get; set; }
        public int UserId { get; set; }
        public System.DateTime Time { get; set; }
        public string SourceLanguage { get; set; }
        public string SourceText { get; set; }
        public string DestinationLanguage { get; set; }
        public string DestinationText { get; set; }
    
        public virtual User User { get; set; }
    }
}
